In [32]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import matplotlib.pyplot as plt
import os
import pandas as pd
import seaborn as sns
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score

import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.preprocessing import PolynomialFeatures

import sklearn.linear_model as skl_lm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis


from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

from time import time
import timeit 

In [9]:
dfes = pd.read_csv('RiverRoad_Quan_RF.csv')
dfes

GRID_ID  qu_dem_MIN  qu_dem_MAX  qu_dem_RANGE  qu_dem_MEAN  qu_dem_STD  \
0      AA-10    0.691847    1.731059      1.039212     1.117221    0.202755   
1      AA-11    0.641888    1.487661      0.845773     1.059745    0.147762   
2      AA-12    0.770032    1.507396      0.737363     1.176038    0.160304   
3      AA-13    0.761148    1.413489      0.652341     1.131694    0.115760   
4      AA-14    0.696000    1.392386      0.696386     1.160470    0.116413   
...      ...         ...         ...           ...          ...         ...   
8606    Z-95    0.851000    1.676798      0.825798     1.409729    0.230505   
8607    Z-96    0.723952    1.662994      0.939042     1.425776    0.219366   
8608    Z-97    0.836438    1.653542      0.817103     1.452142    0.180319   
8609    Z-98    0.997941    1.636024      0.638083     1.461971    0.166600   
8610    Z-99    0.962564    1.649397      0.686833     1.506675    0.148577   

      qu_dem_SUM  qu_dsm_MIN  qu_dsm_MAX  qu_dsm_RANGE  ...  qu_curpl_SUM  \
0     313.939159    0.731374    6.256660      5.525286  ...   1688.477507   
1     295.668776    0.661373    6.679267      6.017894  ...  -1129.404510   
2     329.290651    0.770032    5.681332      4.911300  ...   -994.710507   
3     316.874198    0.761148    1.462370      0.701221  ...  -2264.176594   
4     322.610787    0.667013    1.392386      0.725372  ...   -571.203099   
...          ...         ...         ...           ...  ...           ...   
8606  390.494948    0.851000    1.676798      0.825798  ...    106.915450   
8607  396.365613    0.723952    1.662994      0.939042  ...   -327.422941   
8608  406.599629    0.836438    1.653542      0.817103  ...    279.791020   
8609  406.427984    0.997941    1.636024      0.638083  ...   -313.958618   
8610  420.362367    0.962564    1.649397      0.686833  ...    260.412028   

      qu_curpr_MIN  qu_curpr_MAX  qu_curpr_RANGE  qu_curpr_MEAN  qu_curpr_STD  \
0      -561.943237    585.859314     1147.802551      -6.984654    173.043352   
1      -841.298767    679.957519     1521.256287       0.069758    168.483844   
2      -614.981445    614.381775     1229.363220      -9.649778    201.707961   
3      -577.830017    633.895386     1211.725403      -1.244892    180.105412   
4      -574.029480    501.253113     1075.282593      -1.556956    170.969213   
...            ...           ...             ...            ...           ...   
8606   -692.625366    738.732422     1431.357788       4.547107    170.083954   
8607   -390.115845    542.452454      932.568298      10.324390    134.407219   
8608   -728.279236    753.877563     1482.156799       1.897032    165.294550   
8609   -622.526367    402.200531     1024.726898       4.975549    115.808141   
8610   -444.978790    355.776306      800.755096      15.123050    108.550538   

      qu_curpr_SUM  wetland_type  FID_RiverRd_AOI     wetland  
0     -1941.733846    nonwetland                0  nonwetland  
1        19.392675    nonwetland                0  nonwetland  
2     -2692.288038    nonwetland                0  nonwetland  
3      -347.324849    nonwetland                0  nonwetland  
4      -435.947672    nonwetland                0  nonwetland  
...            ...           ...              ...         ...  
8606   1268.642730        PEM1Rd                1     wetland  
8607   2890.829178        PEM1Rd                1     wetland  
8608    527.374799        PEM1Rd                1     wetland  
8609   1383.202760        PEM1Rd                1     wetland  
8610   4204.208021    nonwetland                0  nonwetland  

[8611 rows x 64 columns]

In [3]:
df_corr = pd.concat([dfes[dfes.columns[1:62]], dfes['FID_RiverRd_AOI']], axis=1)
corr = df_corr.corr()
df_corr = pd.DataFrame(corr['FID_RiverRd_AOI'])

df_corr = df_corr[:-1]
df_corr

FID_RiverRd_AOI
qu_dem_MIN             -0.569517
qu_dem_MAX             -0.517710
qu_dem_RANGE            0.222622
qu_dem_MEAN            -0.533536
qu_dem_STD              0.122975
qu_dem_SUM             -0.533909
qu_dsm_MIN             -0.473204
qu_dsm_MAX             -0.471220
qu_dsm_RANGE           -0.416919
qu_dsm_MEAN            -0.443299
qu_dsm_STD             -0.403611
qu_dsm_SUM             -0.443501
qu_hyddem_MIN          -0.522355
qu_hyddem_MAX          -0.518154
qu_hyddem_RANGE        -0.064559
qu_hyddem_MEAN         -0.530812
qu_hyddem_STD          -0.047181
qu_hyddem_SUM          -0.531178
qu_smdem_MIN           -0.527929
qu_smdem_MAX           -0.546939
qu_smdem_RANGE         -0.194320
qu_smdem_MEAN          -0.537211
qu_smdem_STD           -0.137580
qu_smdem_SUM           -0.537584
qu_asp_MIN             -0.137706
qu_asp_MAX              0.144463
qu_asp_RANGE            0.171251
qu_asp_MEAN             0.018290
qu_asp_STD              0.279583
qu_asp_SUM              0.018180
qu_floAcu_MIN          -0.302199
qu_floAcu_MAX          -0.152481
qu_floAcu_RANGE        -0.149203
qu_floAcu_MEAN         -0.275035
qu_floAcu_STD          -0.150083
qu_floAcu_SUM          -0.274916
qu_floDir_MIN          -0.036580
qu_floDir_MAX           0.125162
qu_floDir_RANGE         0.127407
qu_floDir_MEAN          0.062768
qu_floDir_STD           0.178517
qu_floDir_SUM           0.062424
qu_curv_MIN            -0.380696
qu_curv_MAX             0.248453
qu_curv_RANGE           0.337022
qu_curv_MEAN           -0.003432
qu_curv_STD             0.448222
qu_curv_SUM            -0.003492
qu_curpl_MIN           -0.390999
qu_curpl_MAX            0.242533
qu_curpl_RANGE          0.345143
qu_curpl_MEAN          -0.202742
qu_curpl_STD            0.462017
qu_curpl_SUM           -0.202924
qu_curpr_MIN            0.013042
qu_curpr_MAX           -0.000633
qu_curpr_RANGE         -0.007163
qu_curpr_MEAN          -0.017622
qu_curpr_STD           -0.005184
qu_curpr_SUM           -0.017281

In [22]:
X = dfes.loc[:, ["qu_dem_MIN", "qu_dem_MAX"]]
y = dfes.loc[:, "wetland"]

In [42]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

lda = LinearDiscriminantAnalysis()
model = lda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.79048172 0.77003484 0.76945412 0.79210221 0.78164925]

Avg accuracy: 0.7807444272104607
---Run time is 0.10769759999993767 seconds ---


In [43]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

qda = QuadraticDiscriminantAnalysis()
model = qda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.81427742 0.79268293 0.79210221 0.80836237 0.79674797]

Avg accuracy: 0.8008345786965041
---Run time is 0.07057810000014797 seconds ---


In [25]:
X = dfes.loc[:, ["qu_hyddem_SUM", "qu_dsm_MIN"]]
y = dfes.loc[:, "wetland"]

In [41]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

lda = LinearDiscriminantAnalysis()
model = lda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.79048172 0.77003484 0.76945412 0.79210221 0.78164925]

Avg accuracy: 0.7807444272104607
---Run time is 0.1243082000000868 seconds ---


In [44]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

qda = QuadraticDiscriminantAnalysis()
model = qda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.81427742 0.79268293 0.79210221 0.80836237 0.79674797]

Avg accuracy: 0.8008345786965041
---Run time is 0.05823560000044381 seconds ---


In [15]:
X = dfes.loc[:, ["qu_dsm_MAX", "qu_dsm_RANGE"]]
y = dfes.loc[:, "wetland"]

In [46]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

lda = LinearDiscriminantAnalysis()
model = lda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.79048172 0.77003484 0.76945412 0.79210221 0.78164925]

Avg accuracy: 0.7807444272104607
---Run time is 0.10384019999992233 seconds ---


In [47]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

qda = QuadraticDiscriminantAnalysis()
model = qda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.81427742 0.79268293 0.79210221 0.80836237 0.79674797]

Avg accuracy: 0.8008345786965041
---Run time is 0.06754339999997683 seconds ---


In [29]:
X = dfes.loc[:, ["qu_hyddem_MIN", "qu_hyddem_MAX"]]
y = dfes.loc[:, "wetland"]

In [48]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

lda = LinearDiscriminantAnalysis()
model = lda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.79048172 0.77003484 0.76945412 0.79210221 0.78164925]

Avg accuracy: 0.7807444272104607
---Run time is 0.10843160000013086 seconds ---


In [49]:
start_time = timeit.default_timer()
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)

qda = QuadraticDiscriminantAnalysis()
model = qda.fit(X, y)

scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

elapsed = timeit.default_timer() - start_time
print("---Run time is %s seconds ---" % elapsed)

Accuracy of each fold: 
 [0.81427742 0.79268293 0.79210221 0.80836237 0.79674797]

Avg accuracy: 0.8008345786965041
---Run time is 0.05847559999983787 seconds ---
